// <auto-generated />
using System;
using AIMemory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIMemory.Data.Migrations
{
    [DbContext(typeof(AIMemoryDbContext))]
    [Migration("20260306194735_AddCodeIndex")]
    partial class AddCodeIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AIMemory.Models.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Artifact", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("artifact_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("PathOrUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("path_or_url");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("ArtifactId");

                    b.HasIndex("SessionId");

                    b.HasIndex("Type");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.CodeFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_id");

                    b.Property<Guid?>("CodeRepositoryRepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("IndexedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_id");

                    b.HasKey("FileId");

                    b.HasIndex("CodeRepositoryRepositoryId");

                    b.HasIndex("Language");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("RepositoryId", "FilePath")
                        .IsUnique();

                    b.ToTable("code_files", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.CodeRepository", b =>
                {
                    b.Property<Guid>("RepositoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_id");

                    b.Property<string>("DefaultBranch")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_branch");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_count");

                    b.Property<string>("IndexedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<int>("SymbolCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("symbol_count");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("RepositoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SourceType");

                    b.ToTable("code_repositories", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.CodeSymbol", b =>
                {
                    b.Property<Guid>("SymbolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol_id");

                    b.Property<Guid?>("CodeFileFileId")
                        .HasColumnType("TEXT");

                    b.Property<long>("EndByte")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_byte");

                    b.Property<int>("EndLine")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_line");

                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_id");

                    b.Property<string>("IndexedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ParentSymbolKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_symbol_key");

                    b.Property<string>("QualifiedName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("qualified_name");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_id");

                    b.Property<string>("Signature")
                        .HasColumnType("TEXT")
                        .HasColumnName("signature");

                    b.Property<long>("StartByte")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_byte");

                    b.Property<int>("StartLine")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_line");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("SymbolKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol_key");

                    b.HasKey("SymbolId");

                    b.HasIndex("CodeFileFileId");

                    b.HasIndex("FileId");

                    b.HasIndex("Kind");

                    b.HasIndex("Name");

                    b.HasIndex("QualifiedName");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SymbolKey");

                    b.ToTable("code_symbols", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.IngestionLogEntry", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<long>("RecordOffset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("record_offset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("Source");

                    b.HasIndex("SourcePath");

                    b.ToTable("ingestion_log", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<decimal?>("CostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_usd");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<int?>("TokenIn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_in");

                    b.Property<int?>("TokenOut")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_out");

                    b.HasKey("MessageId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Model");

                    b.HasIndex("Provider");

                    b.HasIndex("SessionId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.MessageEmbedding", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Dimensions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dimensions");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("embedding");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("MessageId");

                    b.HasIndex("SessionId");

                    b.ToTable("message_embeddings", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_archived");

                    b.Property<string>("Project")
                        .HasColumnType("TEXT")
                        .HasColumnName("project");

                    b.Property<string>("Repo")
                        .HasColumnType("TEXT")
                        .HasColumnName("repo");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("SessionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Project");

                    b.HasIndex("Repo");

                    b.HasIndex("Source");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.ToolCall", b =>
                {
                    b.Property<Guid>("ToolCallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_call_id");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("arguments_json");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_json");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.HasKey("ToolCallId");

                    b.HasIndex("SessionId");

                    b.HasIndex("ToolName");

                    b.ToTable("tool_calls", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Artifact", b =>
                {
                    b.HasOne("AIMemory.Models.Entities.Session", null)
                        .WithMany("Artifacts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIMemory.Models.Entities.CodeFile", b =>
                {
                    b.HasOne("AIMemory.Models.Entities.CodeRepository", null)
                        .WithMany("Files")
                        .HasForeignKey("CodeRepositoryRepositoryId");
                });

            modelBuilder.Entity("AIMemory.Models.Entities.CodeSymbol", b =>
                {
                    b.HasOne("AIMemory.Models.Entities.CodeFile", null)
                        .WithMany("Symbols")
                        .HasForeignKey("CodeFileFileId");
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Message", b =>
                {
                    b.HasOne("AIMemory.Models.Entities.Session", null)
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIMemory.Models.Entities.ToolCall", b =>
                {
                    b.HasOne("AIMemory.Models.Entities.Session", null)
                        .WithMany("ToolCalls")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIMemory.Models.Entities.CodeFile", b =>
                {
                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("AIMemory.Models.Entities.CodeRepository", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Session", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Messages");

                    b.Navigation("ToolCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
