// <auto-generated />
using System;
using AIMemory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIMemory.Data.Migrations
{
    [DbContext(typeof(AIMemoryDbContext))]
    [Migration("20260508205558_AddDistributedIdentity")]
    partial class AddDistributedIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AIMemory.Models.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("ApiKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key_prefix");

                    b.Property<string>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scopes");

                    b.HasKey("ApiKeyId");

                    b.HasIndex("IsActive");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Artifact", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("artifact_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("PathOrUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("path_or_url");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("ArtifactId");

                    b.HasIndex("SessionId");

                    b.HasIndex("Type");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.CodeFile", b =>
                {
                    b.Property<string>("ContentSha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_sha256");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("FirstSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.HasKey("ContentSha256");

                    b.HasIndex("Language");

                    b.ToTable("code_files", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.CodeSymbol", b =>
                {
                    b.Property<Guid>("SymbolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol_id");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_sha256");

                    b.Property<long>("EndByte")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_byte");

                    b.Property<int>("EndLine")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_line");

                    b.Property<string>("IndexedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ParentSymbolKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_symbol_key");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("QualifiedName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("qualified_name");

                    b.Property<string>("Signature")
                        .HasColumnType("TEXT")
                        .HasColumnName("signature");

                    b.Property<long>("StartByte")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_byte");

                    b.Property<int>("StartLine")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_line");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("SymbolKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol_key");

                    b.HasKey("SymbolId");

                    b.HasIndex("ContentSha256");

                    b.HasIndex("Kind");

                    b.HasIndex("Name");

                    b.HasIndex("ProjectId");

                    b.HasIndex("QualifiedName");

                    b.HasIndex("SymbolKey");

                    b.ToTable("code_symbols", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.FileLocation", b =>
                {
                    b.Property<string>("HostId")
                        .HasColumnType("TEXT")
                        .HasColumnName("host_id");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("RelPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("rel_path");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_sha256");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("FirstSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.HasKey("HostId", "ProjectId", "RelPath");

                    b.HasIndex("ContentSha256");

                    b.HasIndex("ProjectId");

                    b.ToTable("file_locations", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Host", b =>
                {
                    b.Property<string>("HostId")
                        .HasColumnType("TEXT")
                        .HasColumnName("host_id");

                    b.Property<string>("FirstSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("friendly_name");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_local");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("OsKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("os_kind");

                    b.HasKey("HostId");

                    b.HasIndex("FriendlyName")
                        .IsUnique();

                    b.ToTable("hosts", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.IngestionLogEntry", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_name");

                    b.Property<long>("RecordOffset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("record_offset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("Source");

                    b.HasIndex("SourcePath");

                    b.ToTable("ingestion_log", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<decimal?>("CostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_usd");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<int?>("TokenIn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_in");

                    b.Property<int?>("TokenOut")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_out");

                    b.HasKey("MessageId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Model");

                    b.HasIndex("Provider");

                    b.HasIndex("SessionId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.MessageEmbedding", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Dimensions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dimensions");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("embedding");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("MessageId");

                    b.HasIndex("SessionId");

                    b.ToTable("message_embeddings", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Pairing", b =>
                {
                    b.Property<Guid>("PairingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("pairing_id");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key_id");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("friendly_name");

                    b.Property<string>("HostId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("host_id");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_revoked");

                    b.Property<string>("LastContactAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_contact_at");

                    b.Property<string>("PairedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("paired_at");

                    b.HasKey("PairingId");

                    b.HasIndex("HostId")
                        .IsUnique()
                        .HasDatabaseName("ux_pairings_host_id")
                        .HasFilter("is_revoked = 0");

                    b.ToTable("pairings", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("CanonicalRemoteUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_remote_url");

                    b.Property<string>("DefaultBranch")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_branch");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_count");

                    b.Property<string>("FirstSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("IdentityKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("identity_kind");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("RootCommitSha")
                        .HasColumnType("TEXT")
                        .HasColumnName("root_commit_sha");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<int>("SymbolCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("symbol_count");

                    b.HasKey("ProjectId");

                    b.HasIndex("CanonicalRemoteUrl");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_archived");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_name");

                    b.Property<string>("Project")
                        .HasColumnType("TEXT")
                        .HasColumnName("project");

                    b.Property<string>("Repo")
                        .HasColumnType("TEXT")
                        .HasColumnName("repo");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("SessionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("MachineName");

                    b.HasIndex("Project");

                    b.HasIndex("Repo");

                    b.HasIndex("Source");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.ToolCall", b =>
                {
                    b.Property<Guid>("ToolCallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_call_id");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("arguments_json");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_json");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.HasKey("ToolCallId");

                    b.HasIndex("SessionId");

                    b.HasIndex("ToolName");

                    b.ToTable("tool_calls", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Artifact", b =>
                {
                    b.HasOne("AIMemory.Models.Entities.Session", null)
                        .WithMany("Artifacts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Message", b =>
                {
                    b.HasOne("AIMemory.Models.Entities.Session", null)
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIMemory.Models.Entities.ToolCall", b =>
                {
                    b.HasOne("AIMemory.Models.Entities.Session", null)
                        .WithMany("ToolCalls")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Session", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Messages");

                    b.Navigation("ToolCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
