// <auto-generated />
using System;
using AIMemory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIMemory.Data.Migrations
{
    [DbContext(typeof(AIMemoryDbContext))]
    [Migration("20260303174723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AIMemory.Models.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Artifact", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("artifact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("PathOrUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("path_or_url");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("ArtifactId");

                    b.HasIndex("SessionId");

                    b.HasIndex("Type");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.IngestionLogEntry", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<long>("RecordOffset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("record_offset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("Source");

                    b.HasIndex("SourcePath");

                    b.ToTable("ingestion_log", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<decimal?>("CostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<int?>("TokenIn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_in");

                    b.Property<int?>("TokenOut")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_out");

                    b.HasKey("MessageId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Model");

                    b.HasIndex("Provider");

                    b.HasIndex("SessionId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.MessageEmbedding", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Dimensions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dimensions");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("embedding");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("MessageId");

                    b.HasIndex("SessionId");

                    b.ToTable("message_embeddings", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_archived");

                    b.Property<string>("Project")
                        .HasColumnType("TEXT")
                        .HasColumnName("project");

                    b.Property<string>("Repo")
                        .HasColumnType("TEXT")
                        .HasColumnName("repo");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("SessionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Project");

                    b.HasIndex("Repo");

                    b.HasIndex("Source");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.ToolCall", b =>
                {
                    b.Property<Guid>("ToolCallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_call_id");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("arguments_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_json");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.HasKey("ToolCallId");

                    b.HasIndex("SessionId");

                    b.HasIndex("ToolName");

                    b.ToTable("tool_calls", (string)null);
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Artifact", b =>
                {
                    b.HasOne("AIMemory.Models.Entities.Session", null)
                        .WithMany("Artifacts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Message", b =>
                {
                    b.HasOne("AIMemory.Models.Entities.Session", null)
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIMemory.Models.Entities.ToolCall", b =>
                {
                    b.HasOne("AIMemory.Models.Entities.Session", null)
                        .WithMany("ToolCalls")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIMemory.Models.Entities.Session", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Messages");

                    b.Navigation("ToolCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
